Validando Endpoint

diff --git a/.github/actions/cosmosdb-backup/action.yml b/.github/actions/cosmosdb-backup/action.yml
--- a/.github/actions/cosmosdb-backup/action.yml
+++ b/.github/actions/cosmosdb-backup/action.yml
@@ -98,8 +98,36 @@ runs:
           EXPORT STORAGE_ACCOUNT_KEY=$(az storage account keys list --account-name ${{ inputs.STORAGE_ACCOUNT_NAME }} --query '[0].value' -o tsv)
           echo "Iniciando Job de backup"
           python ${{ github.action_path }}/"${{ inputs.action }}".py 
+  
+          # OUTPUT_FILE=$(find . -type f -name "cosmosdb_nosql_backup_*.json" | sort | tail -n 1)
+          # if [ -f "$OUTPUT_FILE" ]; then
+          #   echo "output-file=$OUTPUT_FILE" >> $GITHUB_ENV
+          # else
+          #   echo "Error: Output file not found!"
+          #   exit 1
+          # fi
+      shell: bash
+    
+    - name: Azure CLI script
+      uses: azure/cli@v2
+      with:
+        azcliversion: latest
+        inlineScript: |
           chmod +x  ${{ github.action_path }}/"${{ inputs.action }}".sh
           ${{ github.action_path }}/azcopy.sh
-      
-  
-   
+    
+    # - name: Upload file to Azure Storage
+    #   if: ${{ inputs.action == 'backup' }}
+    #   run: |
+    #     if [ -f "$OUTPUT_FILE" ]; then
+    #       az storage blob upload \
+    #           --account-name ${{ inputs.STORAGE_ACCOUNT_NAME }} \
+    #           --container-name ${{ inputs.STORAGE_CONTAINER }} \
+    #           --file "$OUTPUT_FILE" \
+    #           --name "$(basename "$OUTPUT_FILE")" \
+    #           --auth-mode login
+    #     else
+    #       echo "Error: Output file not found for upload!"
+    #       exit 1
+    #     fi
+    #   shell: bash
